services:
  dotnetapi:
    image: dotnetapi
    container_name: dotnetapi
    build:
      context: .
      dockerfile: DotNetApi/Dockerfile
    ports:
      - 8080:8080
    environment:
      DatabaseConnection__Host: postgres
    depends_on:
      - postgres
      - flyway
  
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: dotnetapi
      POSTGRES_PASSWORD: postgres
        
  flyway:
    image: flyway/flyway
    container_name: flyway
    command: -url=jdbc:postgresql://postgres:5432/dotnetapi -user=postgres -password=postgres -connectRetries=5 migrate
    volumes:
      - ./Sql:/flyway/sql
    environment:
      - FLYWAY_LOCATIONS=filesystem:/flyway/sql
    depends_on:
      - postgres

  toxiproxy:
    image: ghcr.io/shopify/toxiproxy
    container_name: toxiproxy
    ports:
      - "8474:8474"
      - "8666:8666"
  