services:
  dotnetapi:
    image: dotnetapi
    build:
      context: .
      dockerfile: DotNetApi/Dockerfile
    depends_on:
      - postgres
      - flyway
  
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: dotnetapi
      POSTGRES_PASSWORD: postgres
        
  flyway:
    image: flyway/flyway
    command: -url=jdbc:postgresql://postgres:5432/dotnetapi -user=postgres -password=postgres -connectRetries=5 migrate
    volumes:
      - ./Sql:/flyway/sql
    depends_on:
      - postgres
